In [1]:
import cv2

In [2]:
import sys

In [3]:
import numpy as np

In [4]:
a1 = np.array([[1,3,5,7],
               [2,4,6,8]])

In [5]:
print (a1)

[[1 3 5 7]
 [2 4 6 8]]


In [6]:
b1 = a1[0:2, 0:3]

In [7]:
print (b1)

[[1 3 5]
 [2 4 6]]


In [8]:
c1 = a1[1:, 1:3]


In [9]:
print(c1)

[[4 6]]


In [10]:
d1 = a1[:,1:]

In [11]:
print (d1)

[[3 5 7]
 [4 6 8]]
